baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  dateFormat = "2 Jan 2006"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Research'
    pageRef = '/research'
    weight = 20
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 30
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

